#!/bin/bash
# CODEX API - Quick Reference Card
# Deployment: Option A (WordPress Integration)
# Domain: https://elidorascodex.com

echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║              CODEX API - QUICK REFERENCE CARD                      ║"
echo "║           WordPress Integration @ elidorascodex.com                ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""
echo "📌 BASE URL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "https://elidorascodex.com/wp-json/tec-tgcr/v1"
echo ""
echo ""
echo "📍 ENDPOINTS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. GET /health"
echo "   Service health check"
echo "   Response: { status: 'ok', cards_available: 7 }"
echo ""
echo "2. GET /cards"
echo "   List all 7 CODEX cards"
echo "   Query: ?search=keyword"
echo ""
echo "3. GET /cards/{slug}"
echo "   Get full card content"
echo "   Example: /cards/codex_chronosphere"
echo ""
echo "4. POST /map-question"
echo "   Map question to relevant cards (POWER ENDPOINT)"
echo "   Body: { 'question': 'your question here' }"
echo "   Response: ranked list of top 5 cards"
echo ""
echo "5. GET /manifest"
echo "   Get knowledge service manifest"
echo ""
echo "6. GET /quick-start"
echo "   Get quick start guide"
echo ""
echo ""
echo "🔗 CURL EXAMPLES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Health check"
echo "curl https://elidorascodex.com/wp-json/tec-tgcr/v1/health"
echo ""
echo "# List all cards"
echo "curl https://elidorascodex.com/wp-json/tec-tgcr/v1/cards"
echo ""
echo "# Search cards"
echo "curl 'https://elidorascodex.com/wp-json/tec-tgcr/v1/cards?search=time'"
echo ""
echo "# Get specific card"
echo "curl https://elidorascodex.com/wp-json/tec-tgcr/v1/cards/codex_chronosphere"
echo ""
echo "# Map a question (POST)"
echo "curl -X POST https://elidorascodex.com/wp-json/tec-tgcr/v1/map-question \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"question\": \"How does time work?\"}'"
echo ""
echo ""
echo "🎴 CODEX CARDS (7 Total)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Core Theory (3):"
echo "  • codex_chronosphere"
echo "  • codex_pac_man_universe"
echo "  • codex_steward_matter_subconscience_self"
echo ""
echo "Nodes (2):"
echo "  • codex_synthetic_introspection"
echo "  • codex_gut_brain_phi_t"
echo ""
echo "Clusters (2):"
echo "  • codex_sleep_token_rain"
echo "  • codex_tdwp"
echo ""
echo ""
echo "🚀 CHATGPT INTEGRATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "OpenAPI Spec: /config/gpt-actions-research.json"
echo "Auth: Bearer token (GitHub PAT)"
echo "Server: https://elidorascodex.com"
echo "Namespace: /wp-json/tec-tgcr/v1/"
echo ""
echo "Steps to import:"
echo "  1. Go to https://chat.openai.com/gpts/editor"
echo "  2. Click 'Configure' → 'Create new action'"
echo "  3. Copy OpenAPI spec from /config/gpt-actions-research.json"
echo "  4. Set Auth: API Key, header 'Authorization: Bearer {GITHUB_PAT}'"
echo "  5. Click 'Test' to verify"
echo ""
echo ""
echo "✅ STATUS: READY FOR PRODUCTION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✓ PHP 8.3.6 installed"
echo "✓ WordPress plugin updated (389 lines)"
echo "✓ 7 CODEX endpoints registered"
echo "✓ OpenAPI spec updated for production"
echo "✓ No syntax errors detected"
echo ""
echo "Next: Deploy updated plugin to elidorascodex.com"
echo ""
